
### Relative Intensity Calibration (wavelength-dependent scaling factor)

* This calibration is not important for absorbtion/transmittion measurements, as they rely on a relative information for with and without a sample under study

* This calibration has to be done with each of two diffraction gratings independently

* Light passing through/reflecting from optical elements will undergo significant changes in intensity at different wavelengthes. For example these are the curves for installed diffraction gratings 
    - [300/500](http://www.gratinglab.com/Products/Product_Tables/Efficiency/Efficiency.aspx?catalog=53-*-270R) 
    - [1200/600](http://www.gratinglab.com/Products/Product_Tables/Efficiency/Efficiency.aspx?catalog=53-*-340R)
    
* Another example:
    - Silver mirrors used in the system are coated with 100 nm protective SiO2 coating. This can introduce corresponding interference pattern. This by itself creates a certain interference in traveling signal.  See [example](https://www.filmetrics.com/reflectance-calculator?wmin=200&wmax=1000&wstep=1&angle=0&pol=s&units=nm&mmat=Air&mat[]=SiO2&d[]=100&smat=Si&sptype=r)
    
* There are many ways to address this type of calibration. See this [link](http://nvlpubs.nist.gov/nistpubs/Legacy/IR/nistir7458.pdf) for various options.    
    
* One of the approaches to account for that is to do calibration using tungsten lamp
    - [link 1](http://eprints.lancs.ac.uk/6736/1/inproc_326.pdf), 
    [link 2](http://www.pro-lite.co.uk/File/blog_driving_calibration_lamp.php)
* Another is to use a calibrated fluorescent standard
    - [link 1](https://www.sigmaaldrich.com/technical-documents/articles/biofiles/certifi-ed-fluorescence.html), 
    [link 2](https://www.sigmaaldrich.com/catalog/product/sigma/69336?lang=en&region=US),
    [link 3](http://www.polysciences.com/default/catalog-products/microspheres-particles/instrument-standards/fluorescence-standards), 
    [link 4](https://www.labsphere.com/labsphere-products-solutions/materials-coatings-2/coatings-materials/fluorescence-materials/)


* We have SLS201 light source from Thorlabs (with tugsten-halogen bulb inside). 
    - It features a relativelly stable color temperature of 2796 K. Unfortunatelly this temperature is not guarantied for the lifetime of the bulb, and will depend on surroundign temerature, hours in operation, etc. However, we assume it does not deviate too much.  
    - Data for spectrum can be downloaded from  [here](https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_ID=7269).
    - Light from the lamp should be directed on to [Lambertian screen](https://en.wikipedia.org/wiki/Lambertian_reflectance), which can be made from unfinished wood, a charcoal. This surface will diffusevelly reflect light from lamp, this reflection can be measured by a spectrometer. Lamp by itself has a non-isotropic radiation, thus spectrum would depend on the lamp position if lamp would be used directly (also lamp fillament has different temperature at differenet parts of the fillament).
    
