### Fluorescence


__Sample stage (under the objective) use:__

  1. Use blue laser
  1. Use blue mirror
  2. Focus on sample with using of Thorlabs camera (use darkest ND filter)
  4. Take measurements for laser line (keep ND filter in path) - exactly what is excitation wavelength - 405 nm or something else. +/- 2 nm can change a lot for Raman
  3. Remove ND filter for actual measurements. Use blue filter!
  5. Slit on 5 for good resolution
  6. Acquisition time can be low for strong signals (0.01-0.1 sec)
  7. In live mode adjust focusing of laser (using objective position control knob) to make the signal detected by Andor camera stronger
  8. Collect data


__Cuvette use:__

  1. Use blue laser. Direct it to a cuvvete entrance
  2. Put sample in cuvvete (liquid, particles in liquid, colloids, powders)
  3. Take background spectum with empty quvette at 90 degree exit
  5. Take spectrum at 90 degree exit with filled quvette

__Fiber optics probe use:__

1. See procedure for reflection and adjust accordingly
2. In this case however, light from sample should be collected by an integrating sphere, instead of using the collimator - collimator (and fiber itself) refracts different colors differently, thus if used directly it will modify the spectrum under study. 


#### General Info

There are three main spectra types (related to fluorescence measurements):

  * Absorbance
  * Exitation
  * Emmission
  
Absorption and Exitation spectra are not the same - Some molecules can absorb light but not emit radiation - see [link 1](https://www.thermofisher.com/us/en/home/life-science/cell-analysis/cell-analysis-learning-center/molecular-probes-school-of-fluorescence/imaging-basics/fundamentals-of-fluorescence-microscopy/physical-properties-that-define-fluorescence.html#ex), [link 2](https://www.researchgate.net/post/Whats_the_difference_between_an_excitation_spectrum_and_an_absorption_spectrum_for_the_same_molecule), [link 3](https://micro.magnet.fsu.edu/primer/lightandcolor/fluoroexcitation.html)

Usually only intensity of emmision spectra does depend on exitaiton wavelength (not the shape of the emission spectra). However this is not true for some other objects - see for example this paper describing [fluorescence of silver/cobalt nanoparticles](https://www.sciencedirect.com/science/article/pii/S1026309812000958) (fig. 6)

The optical spectroscopy setup in Hobbler in designed to use a fixed exitation wavelength (405 or 532nm) and thus is not providing exitation spectra.


