#### General considerations

__Absorption__

When light is passing through a material, energy of light can be absorbed.     [source](http://life.nthu.edu.tw/~labcjw/BioPhyChem/Spectroscopy/spectros.htm)

  * Electrons are promoted to higher orbitals by _ultraviolet or visible light_
  * vibrations are excited by _infrared light_
  * rotations are excited by _microwaves_
  * more options - see this [link](https://www.chem.uci.edu/~dmitryf/manuals/Fundamentals/Fluorescence%20Spectroscopy.pdf)


__Scattering__

When electromagnetic radiation passes through matter, most of the radiation continues in its original direction but a small fraction is scattered in other directions. [source](http://life.nthu.edu.tw/~labcjw/BioPhyChem/Spectroscopy/spectros.htm), [source 2](http://pages.mtu.edu/~scarn/teaching/GE4250/scattering_lecture_slides.pdf)

  * _Elastic (Rayleigh, Mie, Geometric reflections) scattering:_ Light that is scattered at the same wavelength as the incoming light
    - Rayleigh scattering results from the electric polarizability of the particles. The oscillating electric field of a light wave acts on the charges within a particle, causing them to move at the same frequency. The particle therefore becomes a small radiating dipole whose radiation we see as scattered light. [wiki](https://en.wikipedia.org/wiki/Rayleigh_scattering)
    - Rayleigh makes [sky blue](http://hyperphysics.phy-astr.gsu.edu/hbase/atmos/blusky.html)
    - Mie makes [clouds white](http://ww2010.atmos.uiuc.edu/(Gl)/guides/mtr/opt/mch/sct/mie.rxml)
    - [Parameters governing scattering](http://pages.mtu.edu/~scarn/teaching/GE4250/scattering_lecture_slides.pdf) - See pp. 7-10 for info on how size of particle will show which description to use Rayleigh, Mie, or Geometric.
        - [more info on scattering by small particles (Rayleigh vs Mie) ](http://www.phys.ufl.edu/courses/phy4422/spring10/Reports/Light%20Scattering%20by%20Small%20Particles.pdf)
    - For nanoparticles surface plasmons can be excited leading to optical resonance phenomena ([link](https://www.nature.com/articles/lsa201460)).
    - [While drawing the Sun, should you color it in green?](http://solar-center.stanford.edu/SID/activities/GreenSun.html)
  * _Inelastic (Raman, fluorescence) scattering:_ Light that is scattered due to vibrations in molecules or optical phonons in solids is called _Raman scattering_. Raman scattered light is shifted by as much as 4000 cm-1 from the incident light.
  * _Quasi-elastic (Brillouin) scattering:_ (think about Doppler effect) Light that is scattered in transparent solids due to vibrations (phonons) is called _Brillouin scattering:_ Brillouin scattering is typically shifted by 0.1 to 1 cm-1 from the incident light.     
    - [some info](http://www.soest.hawaii.edu/HIGP/Faculty/zinin/Zi-Brillouin.html)
   


__Emission__

Atoms or molecules that are excited to high energy levels can decay to lower levels by emitting radiation (emission or luminescence). [source](http://life.nthu.edu.tw/~labcjw/BioPhyChem/Spectroscopy/spectros.htm)

  * For atoms excited by a _high-temperature energy source_ this light emission is commonly called atomic or optical emission
  * for atoms excited with light it is called atomic fluorescence
  * For molecules
      - it is called fluorescence if the transition is between states of the same spin 
      - phosphorescence if the transition occurs between states of different spin.
  * Electroluminescence is describing an emission of light in a repsonse to electricity (for example LED)
      
