### Absorbance, Absorption, Transmission, Extinction, Scattering


__Cuvette use:__

1. Use white light source (Thorlabs SL201). Direct it's light to cuvette
2. Put sample in cuvvete (liquid, particles in liquid, colloids, powders)
3. Take transmission spectum with empty quvette - "Io"
4. Take transmission spectrum with filled quvette - "It"
5. Take scattered spectrum at 90 degree exit with filled quvette - "Is" if needed

__Optical stand use:__

1. Use white light source (Thorlabs SL201)
2. _Reflectance back to the source:_    
Use a special fiber optics probe designed for reflectance measurement if you are doing those. This probe has a collector of a reflected light around the central core sending an original light. 
    - One can use a reference reflectance material (let say a mirror, to get a reference signal)
    - Then relpace mirror by a sample and collect a signal
3. _Reflecatnce at other angles:_    
One normal fiber optics cable to deliver original light. Another normal cable to collect the reflectance at a desired angle.


__Sample in the way use (absorbance, transmission):__

1. Use white light source (Thorlabs SL201)
2. Allight so it goes toward the spectrometer
3. Take reference spectrum
4. Put sample on the way
5. Take a signal spectum


### Basic theory

__Transmittance:__ $$T = It/Io$$

,where $It$ - transmitted radiation, $Io$ - incident radiation 

__Extinction__

Extinction is also known as __attenuation__ ([link](https://en.wikipedia.org/wiki/Attenuation)) - the gradual loss of flux intensity through a medium

Extinction is characterized by __Absorbance__ - logariphm of the ratio of incident to transmitted radiant power through a material. Sometimes natural, but mostly common (base of 10) ([link](https://en.wikipedia.org/wiki/Attenuation) )

Absorbance is different from __Absorption__ ([link](https://en.wikipedia.org/wiki/Attenuation) ):

  * Absorption refers to the physical process of absorbing light. 
  * Absorbance measures attenuation (of transmitted radiant power), which can be caused by absorption, but also reflection, scattering, and other physical processes.
  $$absorbance = absorption + reflection + scattering$$

$$A = log_{10}(Io/It) = log_{10}(1/T) = -log_{10}(T)$$




#### Formulas


[link](http://sydney.edu.au/science/molecular_bioscience/PHAR2811/Spectrophotometry/Spectrophotometry.ppt%2018.07.08.ppt): Intensity of light decaying exponentially: $$T = \frac{It}{Io} = e^{-\alpha c d}$$, where $\alpha$ is an extinction constant, $c$ is concentration and $d$ is light path length

Taking log on both parts: $$ Ln( \frac{Io}{It})={\alpha c d}$$
Converting to log10 (as absorbance usually defined and reported in 10 base):
$$ Log10( \frac{Io}{It})={\varepsilon c d}$$

Now defining absorbance as 

$$A=-log_{10}(T)$$, we have Beer-Lambert's law: $$A = \varepsilon c d$$


_When using cuvette and colloidal solution (or another similar situtaion):_   
Let say you have a colloidal solution of particles in a reference liquid. 
An equation representing absorbance of a sample (particles) would be calculated from trasmission loses due to sample part (Trasmission losses of liqued+particles - trasmission losses of liquid) 

$$A_{sample} = -log10(Ir/Io - It/Io)$$


#### Some relevant info:

* http://sydney.edu.au/science/molecular_bioscience/PHAR2811/Spectrophotometry/Spectrophotometry.ppt%2018.07.08.ppt
* https://en.wikipedia.org/wiki/Absorption_spectroscopy
* https://chemistry.stackexchange.com/questions/33187/difference-between-absorption-spectroscopy-and-extinction-spectroscopy
* https://pubs.acs.org/doi/abs/10.1021/jp309272b
* http://astrowww.phys.uvic.ca/~tatum/stellatm/atm5.pdf
* http://elchem.kaist.ac.kr/vt/chem-ed/spec/spectros.htm
* http://elchem.kaist.ac.kr/vt/chem-ed/spec/beerslaw.htm
* https://nanocomposix.com/pages/gold-nanoparticles-optical-properties
* https://nanocomposix.com/pages/useful-terminology#extinction
* http://curry.eas.gatech.edu/Courses/6140/ency/Chapter9/Ency_Atmos/Reflectance_Albedo_Surface.pdf

